language: julia

os:
  - windows

julia:
  - 1.5
codecov: true

notifications:
  email:
    - omastto1@fel.cvut.cz

# script:
#   - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("FiniteHorizonPOMDPs"; coverage=true)'

# after_success:
#   # Install required packages for coverage and documentation
#   - julia --project -e 'import Pkg; Pkg.add("Coverage");'
#   - julia --project -e 'import Pkg; Pkg.add("Documenter"); Pkg.add("DocumenterTools");'

#     # Submit test coverage report
#   - julia --project -e 'using Coverage; Codecov.submit(Codecov.process_folder())'

#   # Build and deploy documentation
#   - julia --project ./docs/make.jl


after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  allow_failures:
    - os: windows
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("FiniteHorizonPOMDPs"; coverage=true)'
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl